-- filings.db schema
-- Populated by scrapers, read by the evaluator.

CREATE TABLE IF NOT EXISTS scraper_runs (
    run_id          TEXT PRIMARY KEY,
    parent_run_id   TEXT REFERENCES scraper_runs(run_id),
    worker_id       INTEGER,        -- NULL on run row, 1/2/3... on worker rows
    country         TEXT,           -- NULL on worker rows
    started_at      DATETIME,
    finished_at     DATETIME,
    status          TEXT,           -- RUNNING | SUCCESS | FAILED
    files_scraped   INTEGER DEFAULT 0,  -- meaningful on worker rows
    config          TEXT,           -- JSON blob, NULL on worker rows
    worker_count    INTEGER         -- NULL on worker rows
);

CREATE TABLE IF NOT EXISTS companies (
    company_id      TEXT PRIMARY KEY,
    name            TEXT,
    ticker          TEXT,
    exchange        TEXT,
    country         TEXT,
    updated_at      DATETIME
);

CREATE TABLE IF NOT EXISTS filings (
    filing_id        TEXT PRIMARY KEY,   -- UUID generated by scraper
    company_id       TEXT NOT NULL REFERENCES companies(company_id),
    fiscal_year      INTEGER NOT NULL,
    filing_date      DATE,
    reporting_date   DATE,
    reporting_period TEXT,
    UNIQUE (company_id, fiscal_year)
);

CREATE TABLE IF NOT EXISTS filing_files (
    file_id         TEXT PRIMARY KEY,   -- UUID generated by scraper
    filing_id       TEXT NOT NULL REFERENCES filings(filing_id),
    run_id          TEXT NOT NULL REFERENCES scraper_runs(run_id),
    worker_id       INTEGER,            -- which worker downloaded this file
    file_type       TEXT NOT NULL,      -- PDF | XBRL | ...
    form_type       TEXT,               -- 10-K | 10-K405 | 10-KSB | ...
    gcs_path        TEXT,
    url             TEXT,
    scrape_status   TEXT NOT NULL,      -- PENDING | SCRAPED | FAILED
    scraped_at      DATETIME,
    UNIQUE (filing_id, file_type, form_type)
);

-- Indexes for read paths
CREATE INDEX IF NOT EXISTS idx_filings_company_year
    ON filings(company_id, fiscal_year);

CREATE INDEX IF NOT EXISTS idx_filing_files_filing_id
    ON filing_files(filing_id);

CREATE INDEX IF NOT EXISTS idx_filing_files_status
    ON filing_files(scrape_status);
